#!/usr/bin/env bash
# Pre-commit hook for Git repos.
# Andrew Benson (14-May-2026)

# Directory containing individual pre-commit scripts
HOOKS_DIR=".git/hooks/pre-commit.d"

# Exit immediately if any script fails
set -e

# Set extended globbing.
shopt -s extglob

# Run every executable file in the directory
for hook in "$HOOKS_DIR"/!(*~); do
    if [ -x "$hook" ]; then
        echo "Running hook: $(basename "$hook")"
        "$hook" || exit 1
    fi
done

exit 0
